[package]
name = "hello_optimizer_maturin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hello_optimizer_maturin"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
assert_approx_eq = "1.1.0"